name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: aceforeverd
            dockerfile: Dockerfile

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build --no-cache . --file ${{ matrix.dockerfile }} --tag ${{ matrix.image }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Decide Push
        run: |
          if [[ ${{ github.event_name }} = 'push' ]]; then
            echo "PUSH=true" >> $GITHUB_ENV
          else
            echo "PUSH=false" >> $GITHUB_ENV
          fi

      - name: Decide the Tag
        if: ${{ github.event_name == 'push' }}
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}"

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "docker" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=${VERSION#v}

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          GHCR_TAG="$IMAGE_ID:$VERSION"
          echo "GitHub Docker Registry Tag: $GHCR_TAG"
          echo "COMMIT=${{ github.sha }}"

          echo "GHCR_TAG=$GHCR_TAG" >> $GITHUB_ENV

      - name: Build And Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ env.PUSH }}
          platforms: linux/amd64
          tags: |
            ${{ env.GHCR_TAG }}
