name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: aceforeverd
            dockerfile: Dockerfile
          - image: aceforeverd-debian
            dockerfile: Dockerfile.debian


    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build --no-cache . --file ${{ matrix.dockerfile }} --tag ${{ matrix.image }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name = 'push'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image to GitHub Container Registry
        if: github.event_name == 'push'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag ${{ matrix.image }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
